# Single pod deployment
apiVersion: v1
kind: Pod
metadata:
  name: bash-pod
  namespace: misc
spec:
  restartPolicy: Never
  containers:
    - name: bash
      image: bash
      command: ["echo", "hello world"]
