helmDefaults:
  wait: true
  timeout: 300
  createNamespace: true

releases:
  # System
  - name: traefik-dashboard
    namespace: kube-system
    chart: ./system/traefik-dashboard
    labels:
      tier: system

  # Applications
  - name: glance
    namespace: apps
    chart: ./apps/glance
    labels:
      tier: apps
    values:
      - ingress:
          host: glance.kube.home

  # - name: jellyfin
  #   namespace: media
  #   chart: ./apps/jellyfin
  #   labels:
  #     tier: apps
  #   values:
  #     - ./apps/jellyfin/values.yaml

  # - name: metube
  #   namespace: media
  #   chart: ./apps/metube
  #   labels:
  #     tier: apps
  #   values:
  #     - ./apps/metube/values.yaml
  #   needs:
  #     - media/jellyfin

  # - name: filebrowser
  #   namespace: media
  #   chart: ./apps/filebrowser
  #   labels:
  #     tier: apps
  #   values:
  #     - ./apps/filebrowser/values.yaml
  #   needs:
  #     - media/jellyfin

  - name: gotify
    namespace: apps
    chart: ./apps/gotify
    labels:
      tier: apps
    values:
      - ingress:
          host: gotify.kube.home

  - name: ollama
    namespace: apps
    chart: ./apps/ollama
    labels:
      tier: apps
    values:
      - ingress:
          host: ollama.kube.home

  - name: open-webui
    namespace: apps
    chart: ./apps/open-webui
    labels:
      tier: apps
    values:
      - ingress:
          host: ai.kube.home
    needs:
      - apps/ollama

  - name: whoami
    namespace: apps
    chart: ./apps/whoami
    labels:
      tier: ops
    values:
      - ingress:
          host: whoami.kube.home
