replicaCount: 1

image:
  repository: ollama/ollama
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 11434

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  host: ollama
  paths:
    - path: /
      pathType: Prefix

persistence:
  enabled: true
  storageClass: "local-path"
  accessMode: ReadWriteOnce
  size: 10Gi

env: []
